### ISSUE TITLE
Opening parentheses causes juman++ v2 to return invalid output

### ISSUE THREAD

**Issue by olsgaard** [ku-nlp/jumanpp#97] opened 2018-07-16 13:22 UTC
When tagging documents containing single-width opening parentheses, juman++ returns a tag, with no type or subtype defined. Single-width closing parentheses are correctly tagged as 未定義語 15 その他 1.

How to reproduce from commandline / bash
```
[usr@sys ~]$ echo "()（"|jumanpp
( * * 0 0 0 0 記号 0 特殊 0 "代表表記:( _"
@ ( * * 0 0 0 0 記号 0 特殊 0 "代表表記:( _"
@ ( * * 0 0 0 0 記号 0 特殊 0 "代表表記:("
@ ( * * 0 0 0 0 記号 0 特殊 0 "代表表記:("
) ) ) 未定義語 15 その他 1 * 0 * 0 "未知語:未対応文字種 品詞推定:特殊"
（ （ （ 特殊 1 括弧始 3 * 0 * 0 NIL
EOS
[usr@sys ~]$ jumanpp -v
Juman++ Version: 2.0.0-rc2 / Dictionary: 20180202-2cca748 / LM: K:20180217-6c28641 
L:20180221-fd8a4b63 F:20171214-9d125cb
```

The web demo (which uses version 1 at time of writing) outputs a correct tag.

**Comment by eiennohito** [comment] 2018-07-17 02:30
Yep, that's a known bug caused by incorrect import of a Unidic kaomoji dictionary.
I have fixed it in the internal builds.

**Comment by eiennohito** [comment] 2018-07-17 02:31
Anyway, thanks for the report

**Comment by eiennohito** [comment] 2019-08-28 03:03
Fixed in rc3

**Closed** 2019-08-28 03:03 UTC
